apiVersion: v1
kind: Service
metadata:
  name: {{ include "permafrost.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "permafrost.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.master.service.type }}
  selector:
    {{- include "permafrost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: master
  ports:
    - name: http
      port: {{ .Values.master.service.port }}
      targetPort: http
      protocol: TCP
