{{- if .Values.secretKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "permafrost.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "permafrost.labels" . | nindent 4 }}
type: Opaque
stringData:
  PERMAFROST_SECRET_KEY: {{ .Values.secretKey | quote }}
{{- end }}
